// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdTCSPK_Pr2wHIJX51VDHaqHdUh1rLzcw',
    appId: '1:335295431355:web:e70eaadf83e53b34d45f9e',
    messagingSenderId: '335295431355',
    projectId: 'cleaner-app-84a68',
    authDomain: 'cleaner-app-84a68.firebaseapp.com',
    storageBucket: 'cleaner-app-84a68.appspot.com',
    measurementId: 'G-GL8BB6FQ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmaK-fysg8Ft0YzsTcPfxqRYb2LtmcUg',
    appId: '1:335295431355:android:5fb4afc9fbf00a17d45f9e',
    messagingSenderId: '335295431355',
    projectId: 'cleaner-app-84a68',
    storageBucket: 'cleaner-app-84a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxZvIC5RsfoZTYdxQJXJ-93KSVBULcGs',
    appId: '1:335295431355:ios:7f10850ea517c1d4d45f9e',
    messagingSenderId: '335295431355',
    projectId: 'cleaner-app-84a68',
    storageBucket: 'cleaner-app-84a68.appspot.com',
    iosBundleId: 'com.cleanappasec.cleanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxZvIC5RsfoZTYdxQJXJ-93KSVBULcGs',
    appId: '1:335295431355:ios:cef4224375abb75dd45f9e',
    messagingSenderId: '335295431355',
    projectId: 'cleaner-app-84a68',
    storageBucket: 'cleaner-app-84a68.appspot.com',
    iosBundleId: 'com.cleanappasec.cleanapp.RunnerTests',
  );
}
